version: 2
updates:
  - package-ecosystem: npm
    directory: /outputs/aquarium-shop-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /outputs/aquarium-shop-dashboard
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
